config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'favorites_imports/new'
  get 'favorites_imports/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'favorites/new'
  get 'favorites/create'
  get 'categories_select/category_select'
  devise_for :users, controllers: { registrations: "registrations" }
  root :to => 'pages#home'
  post 'categories_select/category_select', to:  'categories_select#create'
  get 'favorites', to: 'favorites#index'
  delete 'favorites', to: 'favorites#destroy'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :favorites do
    collection {post :import, :create}
  end
  resources :favorites, only: :index do
    member do
      post 'toggle_favorite', to: "favorites#toggle_favorite"
    end
  end
  authenticate :user do
  mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  def new
  end
  def index
    @favorites = FavDestination.where(user_id: current_user.id)
    if params[:category_name]
      @favorites = FavDestination.where("category LIKE ?", "%" + params[:category_name] + "%").where(user_id: current_user.id)
    else
      @favorites = FavDestination.where(user_id: current_user.id)
    end
  end

  def toggle_favorite
    @favorite = FavDestination.find_by(id: params[:id])
    current_user.favorited?(@favorite) ? current_user.unfavorite(@favorite) && @favorite.update(visited: false) : current_user.favorite(@favorite) && @favorite.update(visited: true)
    @favorite.update(favorited: true)
  end
  def import
    FavDestination.import(params[:file], current_user.id)
    redirect_to favorites_url, notice: "Destinations imported."
  end
  def destroy
    FavDestination.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: "Destination was removed." }
      format.json { head :no_content }
    end
  end
  def create
    require 'net/http'
    require 'json'

    if params[:id]
      xid = params[:id]
      # get JSON
      result = Net::HTTP.get(URI.parse('https://api.opentripmap.com/0.1/en/places/xid/'+ xid + '?apikey=5ae2e3f221c38a28845f05b63491fa7c34e2bf26d286b76a8e47f69d'))

      # parse JSON
      json = JSON.parse(result)
      name_of_place = json['name']

    if FavDestination.where(user_id: current_user.id).where( name: name_of_place).exists?
      respond_to do |format|
        format.html { redirect_to favorites_url, notice: "Destination already exists." }
        format.json { head :no_content }
      end
    else
      # save data to DB
        FavDestination.create(
          user_id: current_user.id,
          name: json['name'],
          image: json['preview']['source'],
          category: json['kinds'],
          suburb: json['address']['suburb'],
          description: json['wikipedia_extracts']['html'],
          country: json['address']['country'],
          town: json['address']['town'],
          lat: json['point']['lat'],
          lon: json['point']['lon'],
          )
      respond_to do |format|
        format.html { redirect_to favorites_url, notice: "Destination was added." }
        format.json { head :no_content }
      end
    end
    end
  end
  end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/create.html.erb
<head>
  <meta http-equiv="refresh" content="3; URL=/favorites" />
</head>
<h1>Added to favorites!</h1>
<h2>Redirecting...</h2>

app/views/favorites/index.html.erb
<section class="ftco-section">
  <table class="main-table" style="width: 1296px;">
    <tr>
      <td class="side right" style="width: 20%">
        <div class="filtri">
          <h3 style="text-align: center; color: navajowhite">You have visited <%= FavDestination.where(user_id: current_user.id).where(visited: true).count  %> destinations.</h3>
          <h5 style="text-align: center; color: navajowhite">Filtriranje destinacij</h5>
          <ul class="w3-ul w3-card-4" style="border-radius: 10px">
            <% @categories = Category.all %>
            <% @categories.each do |category| %>
              <% category_name = category.name %>
              <% if category_name.count("_") > 0 %>
                <% category_name = category_name.gsub("_", " ") %>
              <% end %>
              <li style="color: whitesmoke"><%= link_to category_name.capitalize, { category_name: category.name } %></a></li>
            <% end %>
            <li style="color: whitesmoke;text-align: center;
              font-size: 20px;
              color: lightblue;"><%= link_to "Clear filters", favorites_path %> </li>
            <li style="text-align: center;">
              <div id="google_translate_element"></div>

              <script type="text/javascript">
                  function googleTranslateElementInit() {
                      new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
                  }
              </script>
              <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
            </li>
          </ul>
        </div>
      </td>
      <td class="side left" style="width: 80%;">
        <table class="right_table">
          <thead>
          </thead>
          <tbody>
          <% @favorites.each do |favorite| %>
            <tr>
              <td>
                <div class="blog-card">
                  <div class="meta">
                    <%
                      require 'net/http'
                      require 'json'
                      lat = favorite.lat
                      lon = favorite.lon
                      result = Net::HTTP.get(URI.parse('https://api.openweathermap.org/data/2.5/weather?lat=' + lat + '&lon=' + lon + '&units=metric&appid=26b649b1c6b9aa6fde403ea73e1b3e10'))
                      json = JSON.parse(result)
                      weather =  json['weather'][0]['description']

                    %>
                    <% if favorite.image.present? %>
                      <% image_url = favorite.image %>
                    <% else %>
                      <% image_url = "https://st4.depositphotos.com/14953852/24787/v/600/depositphotos_247872612-stock-illustration-no-image-available-icon-vector.jpg" %>
                    <% end %>
                    <img class="photo" src="<%= image_url %>">
                    <ul class="details">
                      <% if favorite.country.present? %>
                        <li class="author"><%= favorite.country %></li>
                      <% end %>
                      <% if favorite.town.present? %>
                        <li class="city"><%= favorite.town %></li>
                      <% end %>
                      <% if favorite.suburb.present? %>
                        <li class="status"><%= favorite.suburb %></li>
                      <% end %>
                      <li class="date"><%= favorite.created_at.strftime(' %d %b %Y %H:%M:%S') %></li>
                      <% if favorite.category.present? %>
                        <li class="tags">
                          <ul>
                            <% categories = favorite.category[/[^,]+/] %>
                            <li><%= categories.capitalize || 'Brez kategorije' %></li>
                          </ul>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                  <div id="description">
                    <h1 style="color: darkgray"><i><%= favorite.name.html_safe %></i></h1>
                    <div class="translate"> <%= favorite.description.html_safe %></div>
                    <p><i class="fa fa-umbrella"></i> <%= json['weather'][0]['description'].capitalize %></p>
                    <p><i class="fa fa-temperature"></i> <%= json['main']['temp'] %> C°</p>
                    <div class="read-more">
                      <% if current_user.favorited?(favorite)
                           text = "Visited";
                         else
                           text = "Not visited"
                         end
                      %>
                      <div class="<%= 'fa fa-check' if current_user.favorited?(favorite) %>" data-id="<%= favorite.id %>">
                      </div>
                      <% javascript_pack_tag 'likes' %>
                      <%= link_to text, toggle_favorite_favorite_path(favorite), remote: true, method: :post %>
                      <%= link_to "Delete", { id: favorite.id }, method: :delete %>
                      </div>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </td>
    </tr>
  </table>
</section>

app/views/favorites/new.html.erb
<h1>Favorites#new</h1>
<p>Find me in app/views/favorites/new.html.erb</p>