config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'favorites_imports/new'
  get 'favorites_imports/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'favorites/new'
  get 'favorites/create'
  get 'categories_select/category_select'
  devise_for :users, controllers: { registrations: "registrations" }
  root :to => 'pages#home'
  post 'categories_select/category_select', to:  'categories_select#create'
  get 'favorites', to: 'favorites#index'
  delete 'favorites', to: 'favorites#destroy'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :favorites do
    collection {post :import, :create}
  end
  resources :favorites, only: :index do
    member do
      post 'toggle_favorite', to: "favorites#toggle_favorite"
    end
  end
  authenticate :user do
  mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/favorites_import.rb
class FavoritesImport
  include ActiveModel::Model
  require 'roo'

  attr_accessor :file

  def initialize(attributes={})
    attributes.each { |name, value| send("#{name}=", value) }
  end

  def persisted?
    false
  end

  def open_spreadsheet
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def load_imported_favorites
    spreadsheet = open_spreadsheet
    header = spreadsheet.row(5)
    (6..spreadsheet.last_row).map do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      favorite = FavDestination.find_by_id(row["id"]) || FavDestination.new
      favorite.attributes = row.to_hash
      favorite
    end
  end

  def imported_favorites
    @imported_favorites||= load_imported_favorites
  end

  def save
    if imported_favorites.map(&:valid?).all?
      imported_favorites.each(&:save!)
      true
    else
      imported_favorites.each_with_index do |favorite, index|
        favorite.errors.full_messages.each do |msg|
          errors.add :base, "Row #{index + 6}: #{msg}"
        end
      end
      false
    end
  end

end

app/controllers/favorites_imports_controller.rb
class FavoritesImportsController < ApplicationController
  before_action :authenticate_user!
  def new
    @favorites_import = FavDestination.new
  end

  def create
    @favorites_import = FavDestination.new(params[:file])
    if @favorites_import.save
      redirect_to favorites_path, notice: "Visited destinations imported."
    else
      render :new
    end
  end
end

app/helpers/favorites_imports_helper.rb
module FavoritesImportsHelper
end

app/views/favorites_imports/create.html.erb
<h1>FavoritesImports#create</h1>
<p>Find me in app/views/favorites_imports/create.html.erb</p>

app/views/favorites_imports/new.html.erb
  <section class="ftco-section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 text-center mb-5">
          <h1 class="heading-section">Import your destinations</h1>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4" style="background-color: hsla(120, 90%, 0%, 0.7);border-radius: 15px;padding-top:40px;">
          <div class="login-wrap p-0">
            <div class="form-group">
              <div class="import-info" style="text-align: center">
              <h3>Please provide the following columns:</h3>
              <ul>
                <li>Name - <b>String type</b></li>
                <li>Country -  <b>String type</b></li>
                <li>Town -  <b>String type</b></li>
                <li>Name -  <b>String type</b></li>
                <li>Image -  <b>String type</b></li>
                <li>Latitude -  <b>Integer type</b></li>
                <li>Longitude -  <b>Integer type</b></li>
                <li>Description -  <b>String type</b></li>
              </ul>
              </div>
              <div class="field">
                <%= form_tag import_favorites_path, multipart: true do%>
                  <%= file_field_tag :file %>
                  <%= submit_tag "Import File" %>
                <% end %>
              </div>

</div>
</div>
</div>
</div>
</div>
</section>